{"level":"error","message":"This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason \"undefined\".","name":"UnhandledPromiseRejection","stack":"UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason \"undefined\"."}
{"level":"error","message":"This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason \"undefined\".","name":"UnhandledPromiseRejection","stack":"UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason \"undefined\"."}
{"level":"error","message":"This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason \"undefined\".","name":"UnhandledPromiseRejection","stack":"UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason \"undefined\"."}
{"level":"error","message":"This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason \"undefined\".","name":"UnhandledPromiseRejection","stack":"UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason \"undefined\"."}
{"level":"error","message":"This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason \"undefined\".","name":"UnhandledPromiseRejection","stack":"UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason \"undefined\"."}
{"level":"error","message":"This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason \"undefined\".","name":"UnhandledPromiseRejection","stack":"UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason \"undefined\"."}
{"level":"error","message":"This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason \"undefined\".","name":"UnhandledPromiseRejection","stack":"UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason \"undefined\"."}
{"level":"error","message":"This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason \"undefined\".","name":"UnhandledPromiseRejection","stack":"UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason \"undefined\"."}
{"level":"error","message":"problem","name":"Error","stack":"Error: problem\n    at /Users/Mikhail_Proshin/work/NodeJS_Course/dist/HomeWork_2/routers/Users/get-all-users.js:4:7\n    at Layer.handle [as handle_request] (/Users/Mikhail_Proshin/work/NodeJS_Course/node_modules/express/lib/router/layer.js:95:5)\n    at next (/Users/Mikhail_Proshin/work/NodeJS_Course/node_modules/express/lib/router/route.js:144:13)\n    at Route.dispatch (/Users/Mikhail_Proshin/work/NodeJS_Course/node_modules/express/lib/router/route.js:114:3)\n    at Layer.handle [as handle_request] (/Users/Mikhail_Proshin/work/NodeJS_Course/node_modules/express/lib/router/layer.js:95:5)\n    at /Users/Mikhail_Proshin/work/NodeJS_Course/node_modules/express/lib/router/index.js:284:15\n    at Function.process_params (/Users/Mikhail_Proshin/work/NodeJS_Course/node_modules/express/lib/router/index.js:346:12)\n    at next (/Users/Mikhail_Proshin/work/NodeJS_Course/node_modules/express/lib/router/index.js:280:10)\n    at Function.handle (/Users/Mikhail_Proshin/work/NodeJS_Course/node_modules/express/lib/router/index.js:175:3)\n    at router (/Users/Mikhail_Proshin/work/NodeJS_Course/node_modules/express/lib/router/index.js:47:12)"}
{"level":"error","message":"problem","name":"Error","stack":"Error: problem\n    at /Users/Mikhail_Proshin/work/NodeJS_Course/dist/HomeWork_2/routers/Users/get-all-users.js:4:7\n    at Layer.handle [as handle_request] (/Users/Mikhail_Proshin/work/NodeJS_Course/node_modules/express/lib/router/layer.js:95:5)\n    at next (/Users/Mikhail_Proshin/work/NodeJS_Course/node_modules/express/lib/router/route.js:144:13)\n    at Route.dispatch (/Users/Mikhail_Proshin/work/NodeJS_Course/node_modules/express/lib/router/route.js:114:3)\n    at Layer.handle [as handle_request] (/Users/Mikhail_Proshin/work/NodeJS_Course/node_modules/express/lib/router/layer.js:95:5)\n    at /Users/Mikhail_Proshin/work/NodeJS_Course/node_modules/express/lib/router/index.js:284:15\n    at Function.process_params (/Users/Mikhail_Proshin/work/NodeJS_Course/node_modules/express/lib/router/index.js:346:12)\n    at next (/Users/Mikhail_Proshin/work/NodeJS_Course/node_modules/express/lib/router/index.js:280:10)\n    at Function.handle (/Users/Mikhail_Proshin/work/NodeJS_Course/node_modules/express/lib/router/index.js:175:3)\n    at router (/Users/Mikhail_Proshin/work/NodeJS_Course/node_modules/express/lib/router/index.js:47:12)"}
{"level":"error","message":"problem","name":"Error","stack":"Error: problem\n    at /Users/Mikhail_Proshin/work/NodeJS_Course/dist/HomeWork_2/routers/Users/get-all-users.js:4:7\n    at Layer.handle [as handle_request] (/Users/Mikhail_Proshin/work/NodeJS_Course/node_modules/express/lib/router/layer.js:95:5)\n    at next (/Users/Mikhail_Proshin/work/NodeJS_Course/node_modules/express/lib/router/route.js:144:13)\n    at Route.dispatch (/Users/Mikhail_Proshin/work/NodeJS_Course/node_modules/express/lib/router/route.js:114:3)\n    at Layer.handle [as handle_request] (/Users/Mikhail_Proshin/work/NodeJS_Course/node_modules/express/lib/router/layer.js:95:5)\n    at /Users/Mikhail_Proshin/work/NodeJS_Course/node_modules/express/lib/router/index.js:284:15\n    at Function.process_params (/Users/Mikhail_Proshin/work/NodeJS_Course/node_modules/express/lib/router/index.js:346:12)\n    at next (/Users/Mikhail_Proshin/work/NodeJS_Course/node_modules/express/lib/router/index.js:280:10)\n    at Function.handle (/Users/Mikhail_Proshin/work/NodeJS_Course/node_modules/express/lib/router/index.js:175:3)\n    at router (/Users/Mikhail_Proshin/work/NodeJS_Course/node_modules/express/lib/router/index.js:47:12)"}
{"level":"error","message":"problem","name":"Error","stack":"Error: problem\n    at /Users/Mikhail_Proshin/work/NodeJS_Course/dist/HomeWork_2/routers/Users/get-all-users.js:4:7\n    at Layer.handle [as handle_request] (/Users/Mikhail_Proshin/work/NodeJS_Course/node_modules/express/lib/router/layer.js:95:5)\n    at next (/Users/Mikhail_Proshin/work/NodeJS_Course/node_modules/express/lib/router/route.js:144:13)\n    at Route.dispatch (/Users/Mikhail_Proshin/work/NodeJS_Course/node_modules/express/lib/router/route.js:114:3)\n    at Layer.handle [as handle_request] (/Users/Mikhail_Proshin/work/NodeJS_Course/node_modules/express/lib/router/layer.js:95:5)\n    at /Users/Mikhail_Proshin/work/NodeJS_Course/node_modules/express/lib/router/index.js:284:15\n    at Function.process_params (/Users/Mikhail_Proshin/work/NodeJS_Course/node_modules/express/lib/router/index.js:346:12)\n    at next (/Users/Mikhail_Proshin/work/NodeJS_Course/node_modules/express/lib/router/index.js:280:10)\n    at Function.handle (/Users/Mikhail_Proshin/work/NodeJS_Course/node_modules/express/lib/router/index.js:175:3)\n    at router (/Users/Mikhail_Proshin/work/NodeJS_Course/node_modules/express/lib/router/index.js:47:12)"}
{"level":"error","message":"problem","name":"Error","stack":"Error: problem\n    at /Users/Mikhail_Proshin/work/NodeJS_Course/dist/HomeWork_2/routers/Users/get-all-users.js:4:7\n    at Layer.handle [as handle_request] (/Users/Mikhail_Proshin/work/NodeJS_Course/node_modules/express/lib/router/layer.js:95:5)\n    at next (/Users/Mikhail_Proshin/work/NodeJS_Course/node_modules/express/lib/router/route.js:144:13)\n    at Route.dispatch (/Users/Mikhail_Proshin/work/NodeJS_Course/node_modules/express/lib/router/route.js:114:3)\n    at Layer.handle [as handle_request] (/Users/Mikhail_Proshin/work/NodeJS_Course/node_modules/express/lib/router/layer.js:95:5)\n    at /Users/Mikhail_Proshin/work/NodeJS_Course/node_modules/express/lib/router/index.js:284:15\n    at Function.process_params (/Users/Mikhail_Proshin/work/NodeJS_Course/node_modules/express/lib/router/index.js:346:12)\n    at next (/Users/Mikhail_Proshin/work/NodeJS_Course/node_modules/express/lib/router/index.js:280:10)\n    at Function.handle (/Users/Mikhail_Proshin/work/NodeJS_Course/node_modules/express/lib/router/index.js:175:3)\n    at router (/Users/Mikhail_Proshin/work/NodeJS_Course/node_modules/express/lib/router/index.js:47:12)"}
{"level":"error","message":"problem","name":"Error","stack":"Error: problem\n    at /Users/Mikhail_Proshin/work/NodeJS_Course/dist/HomeWork_2/routers/Users/get-all-users.js:4:7\n    at Layer.handle [as handle_request] (/Users/Mikhail_Proshin/work/NodeJS_Course/node_modules/express/lib/router/layer.js:95:5)\n    at next (/Users/Mikhail_Proshin/work/NodeJS_Course/node_modules/express/lib/router/route.js:144:13)\n    at Route.dispatch (/Users/Mikhail_Proshin/work/NodeJS_Course/node_modules/express/lib/router/route.js:114:3)\n    at Layer.handle [as handle_request] (/Users/Mikhail_Proshin/work/NodeJS_Course/node_modules/express/lib/router/layer.js:95:5)\n    at /Users/Mikhail_Proshin/work/NodeJS_Course/node_modules/express/lib/router/index.js:284:15\n    at Function.process_params (/Users/Mikhail_Proshin/work/NodeJS_Course/node_modules/express/lib/router/index.js:346:12)\n    at next (/Users/Mikhail_Proshin/work/NodeJS_Course/node_modules/express/lib/router/index.js:280:10)\n    at Function.handle (/Users/Mikhail_Proshin/work/NodeJS_Course/node_modules/express/lib/router/index.js:175:3)\n    at router (/Users/Mikhail_Proshin/work/NodeJS_Course/node_modules/express/lib/router/index.js:47:12)"}
{"level":"error","message":"problem","name":"Error","stack":"Error: problem\n    at /Users/Mikhail_Proshin/work/NodeJS_Course/dist/HomeWork_2/routers/Users/get-all-users.js:4:7\n    at Layer.handle [as handle_request] (/Users/Mikhail_Proshin/work/NodeJS_Course/node_modules/express/lib/router/layer.js:95:5)\n    at next (/Users/Mikhail_Proshin/work/NodeJS_Course/node_modules/express/lib/router/route.js:144:13)\n    at Route.dispatch (/Users/Mikhail_Proshin/work/NodeJS_Course/node_modules/express/lib/router/route.js:114:3)\n    at Layer.handle [as handle_request] (/Users/Mikhail_Proshin/work/NodeJS_Course/node_modules/express/lib/router/layer.js:95:5)\n    at /Users/Mikhail_Proshin/work/NodeJS_Course/node_modules/express/lib/router/index.js:284:15\n    at Function.process_params (/Users/Mikhail_Proshin/work/NodeJS_Course/node_modules/express/lib/router/index.js:346:12)\n    at next (/Users/Mikhail_Proshin/work/NodeJS_Course/node_modules/express/lib/router/index.js:280:10)\n    at Function.handle (/Users/Mikhail_Proshin/work/NodeJS_Course/node_modules/express/lib/router/index.js:175:3)\n    at router (/Users/Mikhail_Proshin/work/NodeJS_Course/node_modules/express/lib/router/index.js:47:12)"}
{"level":"error","message":"problem","name":"Error","stack":"Error: problem\n    at /Users/Mikhail_Proshin/work/NodeJS_Course/dist/HomeWork_2/routers/Users/get-all-users.js:4:7\n    at Layer.handle [as handle_request] (/Users/Mikhail_Proshin/work/NodeJS_Course/node_modules/express/lib/router/layer.js:95:5)\n    at next (/Users/Mikhail_Proshin/work/NodeJS_Course/node_modules/express/lib/router/route.js:144:13)\n    at Route.dispatch (/Users/Mikhail_Proshin/work/NodeJS_Course/node_modules/express/lib/router/route.js:114:3)\n    at Layer.handle [as handle_request] (/Users/Mikhail_Proshin/work/NodeJS_Course/node_modules/express/lib/router/layer.js:95:5)\n    at /Users/Mikhail_Proshin/work/NodeJS_Course/node_modules/express/lib/router/index.js:284:15\n    at Function.process_params (/Users/Mikhail_Proshin/work/NodeJS_Course/node_modules/express/lib/router/index.js:346:12)\n    at next (/Users/Mikhail_Proshin/work/NodeJS_Course/node_modules/express/lib/router/index.js:280:10)\n    at Function.handle (/Users/Mikhail_Proshin/work/NodeJS_Course/node_modules/express/lib/router/index.js:175:3)\n    at router (/Users/Mikhail_Proshin/work/NodeJS_Course/node_modules/express/lib/router/index.js:47:12)"}
{"level":"error","message":"problem","name":"Error","stack":"Error: problem\n    at /Users/Mikhail_Proshin/work/NodeJS_Course/dist/HomeWork_2/routers/Users/get-all-users.js:1:479\n    at Layer.handle [as handle_request] (/Users/Mikhail_Proshin/work/NodeJS_Course/node_modules/express/lib/router/layer.js:95:5)\n    at next (/Users/Mikhail_Proshin/work/NodeJS_Course/node_modules/express/lib/router/route.js:144:13)\n    at Route.dispatch (/Users/Mikhail_Proshin/work/NodeJS_Course/node_modules/express/lib/router/route.js:114:3)\n    at Layer.handle [as handle_request] (/Users/Mikhail_Proshin/work/NodeJS_Course/node_modules/express/lib/router/layer.js:95:5)\n    at /Users/Mikhail_Proshin/work/NodeJS_Course/node_modules/express/lib/router/index.js:284:15\n    at Function.process_params (/Users/Mikhail_Proshin/work/NodeJS_Course/node_modules/express/lib/router/index.js:346:12)\n    at next (/Users/Mikhail_Proshin/work/NodeJS_Course/node_modules/express/lib/router/index.js:280:10)\n    at Function.handle (/Users/Mikhail_Proshin/work/NodeJS_Course/node_modules/express/lib/router/index.js:175:3)\n    at router (/Users/Mikhail_Proshin/work/NodeJS_Course/node_modules/express/lib/router/index.js:47:12)"}
{"level":"error","message":"This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason \"undefined\".","name":"UnhandledPromiseRejection","stack":"UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason \"undefined\"."}
{"level":"error","message":"","name":"Error","stack":"Error\n    at /Users/Mikhail_Proshin/work/NodeJS_Course/dist/HomeWork_2/routers/Users/update-user.js:1:507\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)"}
{"level":"error","message":"","name":"Error","stack":"Error\n    at /Users/Mikhail_Proshin/work/NodeJS_Course/dist/HomeWork_2/routers/Users/update-user.js:1:569\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)"}
